### ISSUE TITLE
TLC (Germany) | tlc.de

### ISSUE THREAD

**Issue by Feyagirl** [PreMiD/Presences#1087]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [x] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ...  
.Feyagirl ❤ Horror ❤#4976

**What's the name of the service?**  
Tlc.de

**What should the Presence display?** 

Die presence soll den namen der serie/film anzeigen die man gerade schaut so wie den namen der folge / staffelnummer, und die stunde/minute/sekunde (zeit) anzeigen.
Sorry ich kann kein englisch deswegen die google übersetzung

The presence should show the name of the series / film you are watching as well as the name of the sequence / season number, and the hour / minute / second (time).
Sorry I don't speak english so google translation

**If possible, please provide a logo for the service (512x512 minimum)** 

![Download](https://user-images.githubusercontent.com/61389926/75118472-c5a2c880-567a-11ea-9f2b-58931e4e082d.png)

**Comment by Isa27-0** [comment]
Now I noticed some things I researched about this service:

First, it is not a region-restricted service, because he has his international domain: `www.tlc.com` (here in brazil this URL directs me to the brazilian Discovery site, which has a page for it: `www.discoverybrasil.com/tlc`)

Second, I recommend closing this Issue in favor of a presence for the company's new streaming, Discovery+ (`www.discoveryplus.com`)
