### ISSUE TITLE
Custom Status, but for Nintendo Switch games?

### ISSUE THREAD

**Issue by ThisIsntNath** [PreMiD/Presences#1306]
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Nath#0095

**What's the name of the service?** 
Nintendo Switch

**What should the Presence display?** 
I'm imagining the Custom Status but it says "Nintendo Switch" at the very top instead of "Custom Status". Would be extra cool if I could save presets, so if I want to display that I'm playing Animal Crossing: New Horizons, I can save a preset and load it whenever I want to in the future.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by eggsywashere** [comment]
Sorry you can not change the title since it'd require you to change the connected application. We have tried to do that with different ways but it won't work. If you really want to do something like that, wait for upcoming updates which will eventually bring a custom presence setting in the app itself.
