### ISSUE TITLE
YouTube Music showing wrong timestamps

### ISSUE THREAD

**Issue by Momoske** [PreMiD/Presences#1644]
**Describe the Bug**
When playing a song on YT Music, the timestamp (showing how much time is left in the song is wrong), because it compares to the time that the song has loaded, not the actual entire song time.

**Steps to Reproduce**
1. Start a song
2. Measure the time left between current time and loaded time
3. See that it matches this instead of the whole song time

**Expected Behavior**
Show the actual remaining time instead of loaded time - current time

**Screenshots**
https://imgur.com/a/MPBE1kU (shows 2:04 left, should be about 2:30 - 2:40 if doing maths from the first screenshot)

**Environment**
- OS: Windows 10
- Browser: Microsoft Edge Chromium Canary
- Version: 85.0.529.0

**Comment by doomlerd** [comment]
Can't reproduce.

**Comment by Momoske** [comment]
Here's a link to show it in action: https://gyazo.com/03e0bd20b462f527e666171526636155
It seems like it happens only when the "YTSwag" extension is activated, which I use to get lyrics on my screen and has 2 built-in themes: https://chrome.google.com/webstore/detail/ytswag-better-youtube-mus/paegakmcpjcoihjndpgdbilmjbcjedhd

Is this fixable on your end, or should I contact the extension developer?

**Comment by doomlerd** [comment]
If that's the case then sorry, it came to my attention that the extension modifies YT Muisc's theme, and we can't add support for every case, only the vanilla(default) themes.
Even if you contact the extension developer they'll say the same thing, because it really isn't anybody's fault, you just have to use the default theme (if possible) or stop using that extension.
