### ISSUE TITLE
Album Art on YouTube Music Presence.

### ISSUE THREAD

**Issue by rollorikki1** [PreMiD/Presences#1837]
Is it possible to include Album Art on the YouTube Music presence?

If not, it's okay. But it would be easier to describe the song by including an album art like Spotify.

**Comment by Alanexei** [comment]
Unfortunately, this is not possible to do without breaking Discord's Terms of Service and here's why. 

This image being shown here (which applies to every presence):
![image](https://user-images.githubusercontent.com/20159369/87113155-38c86800-c233-11ea-83a1-43cfb4806e35.png)
was uploaded manually through Discord's developer applications page.

Spotify can show album art because they have an agreement with Discord that allows them to use their own CDN. However, PreMiD on the other hand, does not have a special agreement with Discord, which forces presence developers to upload to Discord's CDN. And according to their TOS, uploading of images to their CDN automatically (in this case, album art) is prohibited.

Hope this helps you understand a little more.
