### ISSUE TITLE
[Presence | Feature Request] Apple Music

### ISSUE THREAD

**Issue by LakshyaShastri** [PreMiD/Presences#2411]
**Is your feature request related to a problem? Please describe.**
The Apple Music rich presence doesn't work with `beta.music.apple.com`

**Describe the solution you'd like**
I'd like the Apple Music rich presence to support the same

**Additional context**
`beta.music.apple.com` has more features, is more stable and overall just works better than `music.apple.com`

**Comment by lachydaves25** [comment]
yes can someone please do this because iTunes is absolute shit when integrating with windows media player and I used the beta website. 
_**this is what I mean by windows media player integration**_
![windows media player integration](https://user-images.githubusercontent.com/37570905/109377378-21073680-791f-11eb-9518-ab010dcf436f.png)

**Comment by ririxidev** [comment]
@N0chteil :^)
