### ISSUE TITLE
[Presence | Bug] Bilibili

### ISSUE THREAD

**Issue by Bejukoro** [PreMiD/Presences#2666]
**Describe the Bug**

The presence is empty when opening any video page on [Bilibili](https://www.bilibili.com/).

**Steps to Reproduce**

1. Install PreMid and enable the Bilibili presence.
2. Visit any video page on Bilibili (the link is in the format like `https://www.bilibili.com/video/*`).
3. Play / Pause the video.

**Expected Behavior**

Show video name and video playback status on my Discord profile.

**Screenshots**

<img width="1061" alt="screenshot" src="https://user-images.githubusercontent.com/42836326/102871111-f90bda80-4478-11eb-9e1f-c0f2df83c891.png">

**Environment**

- OS: Windows 10 / macOS Big Sur (both) 
- Browser: Chrome 
- Version: 87.0.4280.88 (64-bit)

**Comment by WONGY20** [comment]
Having the same issue with /video/, while for clips from /bangumi/, the presence works normally.

**Steps to Reproduce**

1. Install PreMid and enable the Bilibili presence.
2. Visit any video page on Bilibili (the link is in the format like https://www.bilibili.com/video/*).
3. Play / Pause the video.

**Expected Behavior**

Show video name and video playback status on my Discord profile.

**Environment**

* OS: macOS Catalina
* Browser: Chrome/ Firefox (both)
* Version: 89.0.4389.82 (64-bit)/ 86.0.1(64-bit)

**Comment by np2359** [comment]
At line 132 "#v_upinfo > div.u-info > div > a.username"
Change to: "#v_upinfo > div.up-info_right > div.name > a.username"

**Comment by ririxidev** [comment]
@Bas950

**Comment by Bas950** [comment]
@Kotoki1337

**Comment by Kotoki1337** [comment]
I have no time at all. I was try to fix like 3 months ago but there's some weird error may due to my proxy issue. I will try to fix when i back to home next month.

**Comment by Isa27-0** [comment]
It has already been solved (#4352)
