### ISSUE TITLE
AimingPRO | aiming.pro

### ISSUE THREAD

**Issue by Zeerky** [PreMiD/Presences#3390]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**Zeerk#7777** 

**https://aiming.pro/** 

**Current mode, Accuracy, Time** 

**I hope I did this right
![index](https://user-images.githubusercontent.com/81659257/113071811-860ab200-9193-11eb-92d8-96d39ad5d49e.png)
**

**Comment by jamesonknutson** [comment]
Apologies to the maintainer of this repo. This comment is meant only for the author of this issue, @Zeerky 

You contacted me on Discord regarding a job, but left no way for me to reply to you. Please reach out to me on Discord @ Blitz#0387 if your needs are still relevant.

**Comment by ririxidev** [comment]
@jamesonknutson well - I guess you will not find contact with him here since they created account and created this issue so I don't think that they even remember that they have issue here.
![image](https://user-images.githubusercontent.com/9348108/119323987-9749d980-bc7f-11eb-8a44-53042f58d2ff.png)
I'm going to delete your comment since it's not related to Presences.
