### ISSUE TITLE
Ko-Fi | ko-fi.com

### ISSUE THREAD

**Issue by csantos987** [PreMiD/Presences#3811]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

https://ko-fi.com | Ko-Fi

**What should the Presence display?** 

What page a user is on, especially for what Ko-Fi user another is looking at

**If possible, please provide a logo for the service (512x512 minimum)** 

https://uploads-ssl.webflow.com/5c14e387dab576fe667689cf/5ca5bf1dff3c03fbf7cc9b3c_Kofi_logo_RGB_rounded.png

**Comment by dzlandis** [comment]
I am interested in developing the presence for this if nobody else is currently working on it. 😉

**Comment by dzlandis** [comment]
I've essentially completed the presence and everything appears to be functional. There is only one problem that I noticed when developing the presence. It has come to my attention that Ko-Fi has an "NSFW" tag that users can put on their page for certain things. However, Ko-Fi also does not allow most NSFW things and is not a website that would be considered NSFW without further review. My question is if I need to put the NSFW tag in the tags for this presence and if there are any other precautions I need to take because of this.

Links:
[NSFW Tag Info](https://help.ko-fi.com/hc/en-us/articles/360007974034-Using-The-NSFW-Tag)
[Prohibited Content on Ko-fi](https://help.ko-fi.com/hc/en-us/articles/360007937553-Prohibited-Content-and-Uses-of-Ko-fi)

Here's one of the popup things they have for some pages. Some of which (like this image which is just a person with a lightsaber) are clearly not NSFW.
![NSFW Popup Image](https://i.imgur.com/9EzEEVs.png)

Some brief summary quotes:
"Ko-fi must be a safe place for everyone and cannot be a venue for violent, adult, sexual, hateful or illegal content. " - Prohibited Content Page
"The NSFW tag does not permit Ko-fi members to use their page or create content which does not comply with the Ko-fi [Content Guidelines](https://help.ko-fi.com/hc/en-us/articles/360007937553-Illegal-Adult-and-NSFW-Content)." - NSFW Tag Page

So anyway, Ko-Fi's NSFW tag isn't really NSFW as it appears that they don't actually allow true NSFW content on the website? Not really sure, it's very confusing. I suggest you take a look at the links. Please let me know what I am supposed to do 👍🏻  @ririxidev
