### ISSUE TITLE
Presences not showing on the extension

### ISSUE THREAD

**Issue by Nixuge** [PreMiD/Presences#467]
**Describe the bug**
The extension works but the menu with the list of the presences on the extension isn't showing anything

**To Reproduce**
Update the desktop app (tried on a friend's pc and there is no issue)

**Expected behavior**
See the presence list

**Screenshots**
https://daddyfinger.me/WMap3c.png
https://daddyfinger.me/zPNyu4.png
https://daddyfinger.me/sGvntN.png

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest update)
 - Browser: Edge Dev (chromium)
 - Version 79.0.294.1 (Official build) dev (64-bit)

**Additional context**
Happened right after updating the desktop app

**Comment by TrojanerHD** [comment]
I found out that this always happens when you delete a presence via the "trash button" in the extension's menu. The current workaround is to uninstall the PreMiD extension, restart your browser and install the extension again. If you want to remove presences, then do not use the extension's menu. Use the store website instead.

**Comment by Nixuge** [comment]
It's pretty weird, I reinstalled the extension and tried to remove a presence and there is no issue + I never deleted a presence before

**Comment by Nixuge** [comment]
Btw it's working again*
