### ISSUE TITLE
Jellyfin | Music presence being somewhat inconsistent

### ISSUE THREAD

**Issue by StayBlue** [PreMiD/Presences#7117]
### Steps to Reproduce

1. Attempt to play a song (please read additional comments)

### Expected Behavior

Music presence should be consistent and work like shows and movies

### Actual Behavior

A bit buggy and inconsistent

### Page URL

N/A

### Screenshots

**Shows (✅)**
![image](https://user-images.githubusercontent.com/23127866/211666575-4b913dac-69b5-45b4-bf28-13330bef82dd.png)

**Movies (✅)**
![image](https://user-images.githubusercontent.com/23127866/211666794-f2b21b91-3136-4308-a263-7737623bf54b.png)

**Music**
Unknown Artist: 
![image](https://user-images.githubusercontent.com/23127866/211667730-03ef4115-d602-462f-bc0f-6f3400a71f3d.png)

No Cover:
![image](https://user-images.githubusercontent.com/23127866/211667862-3734182e-68f5-41bc-854c-35a29be0ef73.png)

### Operating System

Windows 10

### Browser and Version

Firefox, Version 108.0.2

### Additional Comments

Describing the issue is better than giving steps because this bug is weird. Initially, when opening this issue, I thought music presence didn't work at all, but after testing it a bit more, it seems more finicky than broken.

I'll let the images speak for themselves, but the two big issues I've seen the most are the artist not being picked up even though the metadata is there ("unknown artist') and the cover for the song not showing up.

When I open the web dashboard using my domain instead of my local IP (my server is locally hosted), the music presence doesn't work, while movies and shows work fine. A workaround I have found to this is to play a movie/show and then play a song, but the unknown artist and cover issues still need to be solved.

I'm using the official Jellyfin docker container image (version 10.8.8).

**Comment by alexbcberio** [comment]
Hello, first of all sorry for the long wait-time.

I am not able to reproduce the issue on my Jellyfin instance, the presence uses the server API to obtain the metadata of the item and falls back to "unknown ..." message if the metadata value is not set ([see code](https://github.com/PreMiD/Presences/blob/4897a598c4526ab21e6c42419cf4ea1c192d7f46/websites/J/Jellyfin/presence.ts#L336)). Something similar is done for the image. I can guess that something is not working alright in your set-up, in that case you should be able to check out the errors on the console tab inside the browser developer tools.

I'm using Jellyfin 10.8.9 (as at the moment on writing the reply) and I also have the server on the local network. I use a subdomain to access it.

How have you set up Jellyfin, on a subdomain (<jellyfin.example.com>) or a subpath (<example.com/jellyfin>?
I'm gonna assume you have set it up on a subpath by your additional comments, theoretically it should also work.

The video and audio playback handling logic is very similar, I don't get why movies/shows work alright while music does not work ok.

Please check out this and reply whenever you're free:
- Open the browser developer tools, select the "console" tab and replicate the issue. Then check out any errors and post a pic or copy-paste the text.
  **Note**: there might be errors related to non-premid scripts, we are interested in the ones that are caused by "VM:<numbers>" (show on the top-right side of the error line).
- How have you set-up your jellyfin server, on a dedicated subdomain or a subpath?

**Comment by StayBlue** [comment]
> How have you set up Jellyfin, on a subdomain (<jellyfin.example.com>) or a subpath (<example.com/jellyfin>?
I have Jellyfin set up on both my local IP address (192.168.X.X) on my home network, on my front-facing IP address, and on a subdomain on my domain (jellyfin.example.com). I am able to reproduce the issue on all three of them.

> Note: there might be errors related to non-premid scripts, we are interested in the ones that are caused by "VM:" (show on the top-right side of the error line).
Even when it shows no artist, no title, and no image, there are no errors that show up in my console.

> The original url should be a publicly accessible site, adding ":/" before the protocol (http or https).
This is what came up when I went to the URL: "**song title** does not have an image of type Primary"
This is a bit weird, however, as the image does show clearly on Jellyfin as being there, but for some reason, the extension keeps pulling the wrong image. When I right-click on the image in Jellyfin and use inspect element to get the image URL, the URL uses a completely different ID than the one the extension tried to use.
As an example...
Extension: https://jellyfin.example.com/Items/ABC/Images/Primary
Jellyfin: https://jellyfin.example.com/Items/BCD/Images/Primary

I'm not entirely sure why this is, but if you need anything from me to get to the bottom of this issue, let me know.

**Comment by alexbcberio** [comment]
I think I have been able to reproduce the issue on [Jellyfin's demo instance](https://demo.jellyfin.org/).
Can you verify if it behaves the same as in your instance? The music albumarts do not load while movie/tv-shows do

**Comment by StayBlue** [comment]
> I think I have been able to reproduce the issue on [Jellyfin's demo instance](https://demo.jellyfin.org/).
> 
> 
> 
> Can you verify if it behaves the same as in your instance? The music albumarts do not load while movie/tv-shows do
> 
> 
> 
> Edit: image url reported by the extension "https://demo.jellyfin.org/stable/Items/a794b7c125d436df8dc2d870ad7b7e1e/Images/Primary", albumart used on jellyfin web "https://demo.jellyfin.org/stable/Items/f21ea9ece4e6e26ec26ebfb81b82ad78/Images/Primary?height=70&tag=dea13cb0f8a13503acb359db4c03baff&quality=90"

Yep, that's the issue!

**Comment by alexbcberio** [comment]
Issue is fixed, I've opened a pull request to update the presence and all the checks have passed.

All we're missing are a code-review and approval of the presence-re
