### ISSUE TITLE
brain.fm | my.brain.fm doesn't show detailed presence information

### ISSUE THREAD

**Issue by bramtechs** [PreMiD/Presences#7373]
### Steps to Reproduce

1. Go to https://my.brain.fm/ (you need to be signed in)
2. "Choosing mode" is not shown in presence
3. Go to https://my.brain.fm and choose a mode
4. Song details and activity isn't shown in presence

### Expected Behavior

See song info and activity in Discord presence

### Actual Behavior

Generic presence info is shown

### Page URL

https://my.brain.fm/

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/95661609/1af61eb2-9796-4b5e-a818-44607e37d275)

### Operating System

Debian 12

### Browser and Version

Chrome 113.0.5672.126

### Additional Comments

After looking through the source code, a lot of querySelectors are no longer valid. I will try to fix them in a pull request.

**Comment by bramtechs** [comment]
The problem seems to be resolved by updating invalid querySelectors.

![image](https://github.com/PreMiD/Presences/assets/95661609/5eaa8741-fd29-4816-8437-e3381b5034e3)

**Comment by samf2003** [comment]
Hello,

I am getting the same issue, but in 2025. 

Steps: (exact same)
Go to https://my.brain.fm/ (you need to be signed in)
"Choosing mode" is not shown in presence
Go to https://my.brain.fm/ and choose a mode
Song details and activity isn't shown in presence

Expected Behavior
See song info and activity in Discord presence

Actual Behavior
Generic presence info is shown

Page URL
https://my.brain.fm/

Screenshot:

<img width="537" height="303" alt="Image" src="https://github.com/user-attachments/assets/25dddec0-b9d1-4419-bf07-19abf95c9022" />

Operating System
Windows 11

Browser and Version
Version 140.0.7339.208 (Official Build) (64-bit)

Additional Comments
How do I fix this issue? I have little programming knowledge.

**Comment by bramtechs** [comment]
They must have updated the website again. I'm not subscribed to brain anymore or use premid atm but I hope the query selectors can be updated.
