### ISSUE TITLE
Feds.lol | feds.lol

### ISSUE THREAD

**Issue by ohhq** [PreMiD/Presences#7393]
### Website name

feds.lol

### Website URL

https://feds.lol

### Website logo

https://feds.lol/v4/img/logo.png

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description

this is a biolink service similard to [e-z.bio](https://e-z.bio/) so it would be like 
**"viewing feds.lol + /{username}** of the user

**Comment by addi00000** [comment]
Hello,

I am apart of feds.lol's development team. Due to some demand I am currently working on and almost finsished with a premid presence for feds.lol. Should be making a pull request soon.

Thanks!

![image](https://github.com/PreMiD/Presences/assets/81730200/cd9cae68-511f-404f-a867-d0fe4884cd44)
