### ISSUE TITLE
Remove the display of the youtube home page view

### ISSUE THREAD

**Issue by SippinWoock** [PreMiD/Presences#8246]
### Presence name

youtube

### Description

I think this will help a lot of people, because it will get rid of unnecessary information that you are "watching the main page of youtube", but in fact it is just open in the browser in the background. One of the problems: displaying this unnecessary information overlaps the game you are currently playing.

### Alternatives

I suggest just removing the display that you're "looking at the home page". Or make a switch somehow.

**Comment by tag27** [comment]
> One of the problems: displaying this unnecessary information overlaps the game you are currently playing.

This usually happens because Discord puts the presence that has been active the longest (in this case YouTube) instead of the game that was opened later. If what you want is the function to change which presence you want to show on your profile first, unfortunately this is not supported by Discord, and PreMiD can't do anything about it. The most you can do for now is:
- Close the website and/or the browser
- Shut down PreMiD, either by closing the application or by shutting down the extension.

If the presence still appears, go to the [troubleshooting page](https://docs.premid.app/troubleshooting), and if nothing happens, open a thread in #support on the [Discord server](https://discord.gg/premid).
