### ISSUE TITLE
Reddit | reddit.com - Data not being displayed on certain subreddits

### ISSUE THREAD

**Issue by ION606** [PreMiD/Presences#8293]
### Steps to Reproduce

1. go to https://www.reddit.com/r/discordapp/
2. check your status, it should look like

![image](https://github.com/PreMiD/Presences/assets/58801387/9b46b478-9dc9-4a54-a966-75e35121539b)

### Expected Behavior

The correct subreddit information should be displayed

### Actual Behavior

it just says "browsing.....home"

### Page URL

https://www.reddit.com/r/discordapp/

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/58801387/9b46b478-9dc9-4a54-a966-75e35121539b)

### Operating System

Linux

### Browser and Version

Firefox 124

**Comment by tag27** [comment]
The bug is reproducible 
![image](https://github.com/PreMiD/Presences/assets/68751594/0421bb14-ed29-4ca9-ae9b-7bef135dec3f)
Console:
![image](https://github.com/PreMiD/Presences/assets/68751594/1c9b7b3c-3acd-4b12-a009-70bbbacd74b6)
----------------------
OS: ChromeOS
Browser: Chrome 123.0.6312.112 (64 bits)
