### ISSUE TITLE
DeviantArt | www.deviantart.com

### ISSUE THREAD

**Issue by UPPERCASEuser** [PreMiD/Presences#857]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [x] Does the website feature NSFW content? (e.g. porn, etc...) (partial)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** A user#0001

**What's the name of the service?** DeviantArt

**What should the Presence display?** The art name, the art author and image date

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Hans5958** [comment]
Hey, I will take this one.

Due to the broadness of DeviantArt, not mentioning there are two types of website designs, I will try to finish the core parts first, such as art, profiles, groups, galleries, favorites, etc, and then add the others in preceding updates.

If there are some parts that should be prioritize, please tell me as I have not quite a lot of experience on DA.

*P/S: Why it is listed as NSFW? Most of the art listed is SFW, guys!*

**Comment by frozaum** [comment]
@Hans5958 
![EAbwiy7W4AAh0XX](https://user-images.githubusercontent.com/34042085/71832762-5f41f680-308a-11ea-8a9c-3a2072f57545.jpg)
